default:
    image: hub.ilearned.eu/i-learned/ci-cd/pelican-chrome95-ff94

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
    paths:
        - ".cache/pip"
        - "/var/lib/apt/list"
        - "/var/cache/apt/"

stages:
    - build
    - test
    - lint
    - deploy

pylint:
    stage: lint
    allow_failure: true
    before_script:
        - apt-get update
        - apt-get -y install python3-pip
        - pip3 install virtualenv
        - virtualenv venv
        - source venv/bin/activate
        - python3 -m pip install --upgrade pip
        - pip install -r requirements.txt
    script:
        - pylint $(git ls-files '*.py')

stylelint:
    stage: lint
    allow_failure: true
    before_script:
        - npm install -g stylelint
        - npm install -g stylelint-config-standard-scss
    script:
        - stylelint $(git ls-files '*.scss')

build:
    stage: build
    before_script:
        - apt-get update
        - apt-get -y install python3-pip
        - pip3 install virtualenv
        - virtualenv venv
        - source venv/bin/activate
        - python3 -m pip install --upgrade pip
        - pip install -r requirements.txt
    script:
        - make build
    artifacts:
        paths:
            - output/
lighthouse:
    image: hub.ilearned.eu/i-learned/ci-cd/pelican-chrome95-ff94
    stage: test
    script:
        - lhci autorun --outputDir=public/ --collect.settings.chromeFlags="--no-sandbox"
            || echo "LHCI failed!"
    artifacts:
        paths:
            - lighthouse-results/
    needs:
        - build

netlify-deploy:
    stage: deploy
    before_script:
        - npm install netlify-cli -g
    script:
        - cp _headers output/
        - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --message "$CI_COMMIT_SHORT_SHA : $CI_COMMIT_MESSAGE" --prod --dir output/
    needs:
        - build
    only:
        - main

netlify-test-deploy:
    stage: deploy
    before_script:
        - npm install netlify-cli -g
    script:
        - cp _headers output/
        - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --message "Merge : $CI_MERGE_REQUEST_ID" --dir output/
    needs:
        - build
    only:
        - merge_requests

include:
    -   template: Security/Secret-Detection.gitlab-ci.yml

