default:
  image: hub.ilearned.eu/i-learned/ci-cd/pelican-builder

stages:
  - deploy

prod-deploy-job:
  stage: deploy
  script:
    - apk add --no-cache wget tar
    - wget https://github.com/tdewolff/minify/releases/download/v2.10.0/minify_linux_amd64.tar.gz
    - tar -xf minify_linux_amd64.tar.gz -C /tmp
    - /tmp/minify --html-keep-comments -r -o ./ ./
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$SSH_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - rsync -az --exclude=".git*" --delete -e "ssh -p 53453 -i ~/.ssh/id_ed25519" ./ ci@web.ramle.be:/var/www/ramle.be

  only:
    - master
  tags:
    - AMD64
