default:
    image: hub.ilearned.eu/i-learned/ci-cd/pelican-chrome95-ff94

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
    paths:
        - .cache/pip
        - /var/lib/apt/list
        - /var/cache/apt/
stages:
    - lint
    - build
    - test
    - deploy

before_script:
    - apt-get update

pylint:
    stage: lint
    allow_failure: true
    script:
        - apt-get -y install python3-pip
        - pip3 install virtualenv
        - virtualenv venv
        - source venv/bin/activate
        - python3 -m pip install --upgrade pip
        - pip install -r requirements.txt
        - pylint $(git ls-files '*.py')

stylelint:
    stage: lint
    allow_failure: true
    script:
        - npm install -g stylelint
        - npm install -g stylelint-config-standard-scss
        - stylelint $(git ls-files '*.scss')

build:
    stage: build
    script:
        - apt-get -y install python3-pip
        - pip3 install virtualenv
        - virtualenv venv
        - source venv/bin/activate
        - python3 -m pip install --upgrade pip
        - pip install -r requirements.txt
        - make build
    artifacts:
        paths:
            - output/

lighthouse:
    image: hub.ilearned.eu/i-learned/ci-cd/pelican-chrome95-ff94
    stage: test
    script:
        - lhci autorun --outputDir=public/ --collect.settings.chromeFlags="--no-sandbox" || echo "LHCI failed!"
        - mkdir public
    artifacts:
        paths:
            - lighthouse-results/
    needs:
        - build

netlify-deploy:
    stage: deploy
    script:
        - npm install netlify-cli -g
        - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
    needs:
        - build
    only:
        - main
