default:
    image: hub.ilearned.eu/i-learned/ci-cd/pelican-chrome95-ff94

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
    paths:
        - .cache/pip
        - /var/lib/apt/list
        - /var/cache/apt/
stages:
    - lint
    - build
    - test
    - pages

before_script:
    - apt-get update
    - apt-get -y install python3-pip
    - pip3 install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - python3 -m pip install --upgrade pip
    - pip install -r requirements.txt

pylint:
    stage: lint
    allow_failure: true
    script:
        - pylint $(git ls-files '*.py')

stylelint:
    stage: lint
    allow_failure: true
    script:
        - npm install -g stylelint
        - npm install -g stylelint-config-standard-scss
        - stylelint $(git ls-files '*.scss')

build:
    stage: build
    script:
        - make build
    artifacts:
        paths:
            - output/

lighthouse:
    image: hub.ilearned.eu/i-learned/ci-cd/pelican-chrome95-ff94
    stage: test
    script:
        - lhci autorun --outputDir=public/ --collect.settings.chromeFlags="--no-sandbox" || echo "LHCI failed!"
        - mkdir public
    artifacts:
        paths:
            - lighthouse-results/
    needs:
        - build
pages:
    script:
        - cp -r output/ public/
    needs:
        - build
    artifacts:
        paths:
            - public
    only:
        - main
