name: Stylelint

on: [ push ]

jobs:
    lint:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [ "18.x" ]
        steps:
            -   uses: actions/checkout@v3
            -   name: Set up node ${{ matrix.python-version }}
                uses: actions/setup-python@v3
                with:
                    python-version: ${{ matrix.python-version }}
            -   name: Install dependencies
                run: |
                    npm install stylelint
                    npm install stylelint-config-standard-scss
            -   name: Analysing the code with stylelint
                run: |
                    stylelint $(git ls-files '*.scss')
